name: CI
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run check:format
      - run: npm run build
      - run: npm test
      - name: Comment on PR with broken links
        if: github.event_name == 'pull_request' && hashFiles('broken-links.md') != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr comment $PR_URL --body-file broken-links.md
      - uses: actions/upload-artifact@v4
        with:
          name: public-dist
          path: public

  deploy_preview:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: public-dist
          path: public
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CARTLAND_DEV_STAGING }}
          projectId: cartland-dev-staging