name: Deploy Preview
on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Build and Test
    uses: ./.github/workflows/build-and-test.yml

  deploy_preview:
    name: Deploy Preview
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: public-dist
          path: public
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CARTLAND_DEV_STAGING }}
          projectId: cartland-dev-staging
          channelId: pr-${{ github.event.number }}
