name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run check:format
      - run: npm run build
      - run: npm test
      - uses: actions/upload-artifact@v4
        with:
          name: public-dist
          path: public

  deploy_staging:
    needs: build_and_test
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://cartland-dev-staging.web.app
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: public-dist
          path: public
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CARTLAND_DEV_STAGING }}
          projectId: cartland-dev-staging
          channelId: live

  deploy_production:
    needs: deploy_staging
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://chriscart.land
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: public-dist
          path: public
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_CARTLAND_DEV }}
          projectId: cartland-dev
          channelId: live